from abc import ABC
from typing import Any, Dict, List, Union

from rapidy.constants import DEFAULT_JSON_DECODER
from rapidy.enums import ContentType, HTTPRequestParamType
from rapidy.fields.field_info import RapidyFieldInfo
from rapidy.typedefs import Deprecated, JSONDecoder, NoArgAnyCallable, Undefined, Unset, UnsetType

__all__ = (
    'PathParam',
    'PathParams',
    'Header',
    'Headers',
    'Cookie',
    'Cookies',
    'QueryParam',
    'QueryParams',
    'Body',
)


class RequestParamFieldInfo(RapidyFieldInfo, ABC):
    param_type: HTTPRequestParamType
    extract_single: bool = False


# BASE
class PathBase(RequestParamFieldInfo, ABC):
    param_type = HTTPRequestParamType.path
    can_default = False


class HeaderBase(RequestParamFieldInfo, ABC):
    param_type = HTTPRequestParamType.header


class CookieBase(RequestParamFieldInfo, ABC):
    param_type = HTTPRequestParamType.cookie


class QueryBase(RequestParamFieldInfo, ABC):
    param_type = HTTPRequestParamType.query


# PARAMS
class PathParam(PathBase):
    extract_single = True

    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        alias: Union[str, None, UnsetType] = Unset,
        alias_priority: Union[int, None, UnsetType] = Unset,
        validation_alias: Union[str, None, UnsetType] = Unset,
        serialization_alias: Union[str, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            alias=alias,
            alias_priority=alias_priority,
            validation_alias=validation_alias,
            serialization_alias=serialization_alias,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class PathParams(PathBase):
    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        alias: Union[str, None, UnsetType] = Unset,
        alias_priority: Union[int, None, UnsetType] = Unset,
        validation_alias: Union[str, None, UnsetType] = Unset,
        serialization_alias: Union[str, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            alias=alias,
            alias_priority=alias_priority,
            validation_alias=validation_alias,
            serialization_alias=serialization_alias,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class Header(HeaderBase):
    extract_single = True

    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        alias: Union[str, None, UnsetType] = Unset,
        alias_priority: Union[int, None, UnsetType] = Unset,
        validation_alias: Union[str, None, UnsetType] = Unset,
        serialization_alias: Union[str, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            alias=alias,
            alias_priority=alias_priority,
            validation_alias=validation_alias,
            serialization_alias=serialization_alias,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class Headers(HeaderBase):
    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        alias: Union[str, None, UnsetType] = Unset,
        alias_priority: Union[int, None, UnsetType] = Unset,
        validation_alias: Union[str, None, UnsetType] = Unset,
        serialization_alias: Union[str, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            alias=alias,
            alias_priority=alias_priority,
            validation_alias=validation_alias,
            serialization_alias=serialization_alias,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class Cookie(CookieBase):
    extract_single = True

    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        alias: Union[str, None, UnsetType] = Unset,
        alias_priority: Union[int, None, UnsetType] = Unset,
        validation_alias: Union[str, None, UnsetType] = Unset,
        serialization_alias: Union[str, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            alias=alias,
            alias_priority=alias_priority,
            validation_alias=validation_alias,
            serialization_alias=serialization_alias,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class Cookies(CookieBase):
    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class QueryParam(QueryBase):
    extract_single = True

    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        alias: Union[str, None, UnsetType] = Unset,
        alias_priority: Union[int, None, UnsetType] = Unset,
        validation_alias: Union[str, None, UnsetType] = Unset,
        serialization_alias: Union[str, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            alias=alias,
            alias_priority=alias_priority,
            validation_alias=validation_alias,
            serialization_alias=serialization_alias,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class QueryParams(QueryBase):
    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )


class Body(RequestParamFieldInfo):
    param_type = HTTPRequestParamType.body

    def __init__(
        self,
        default: Any = Undefined,
        *,
        default_factory: Union[NoArgAnyCallable, None, UnsetType] = Unset,
        title: Union[str, None, UnsetType] = Unset,
        description: Union[str, None, UnsetType] = Unset,
        gt: Union[float, None, UnsetType] = Unset,
        ge: Union[float, None, UnsetType] = Unset,
        lt: Union[float, None, UnsetType] = Unset,
        le: Union[float, None, UnsetType] = Unset,
        min_length: Union[int, None, UnsetType] = Unset,
        max_length: Union[int, None, UnsetType] = Unset,
        pattern: Union[str, None, UnsetType] = Unset,
        discriminator: Union[str, None, UnsetType] = Unset,
        strict: Union[bool, None, UnsetType] = Unset,
        multiple_of: Union[float, None, UnsetType] = Unset,
        allow_inf_nan: Union[bool, None, UnsetType] = Unset,
        max_digits: Union[int, None, UnsetType] = Unset,
        decimal_places: Union[int, None, UnsetType] = Unset,
        deprecated: Union[Deprecated, str, bool, None, UnsetType] = Unset,
        examples: Union[List[Any], None, UnsetType] = Unset,
        json_schema_extra: Union[Dict[str, Any], None, UnsetType] = Unset,
        validate: bool = True,
        content_type: Union[str, ContentType] = ContentType.json,
        check_content_type: bool = True,
        json_decoder: JSONDecoder = DEFAULT_JSON_DECODER,
        **extra: Any,
    ) -> None:
        super().__init__(
            default,
            default_factory=default_factory,
            title=title,
            description=description,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            min_length=min_length,
            max_length=max_length,
            pattern=pattern,
            discriminator=discriminator,
            strict=strict,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            deprecated=deprecated,
            examples=examples,
            json_schema_extra=json_schema_extra,
            validate=validate,
            **extra,
        )

        self.content_type = content_type
        self.json_decoder = json_decoder
        self.check_content_type = check_content_type
